### ISSUE TITLE
LifeCycleMethodNotFoundException

### ISSUE THREAD

**Issue by sambatriste** [nablarch/nablarch-fw-scoped-dicontainer#4]
特に使用されていないようで、AnnotationMemberFactory等の動作をみると、
この例外をスローすべき箇所もないように見えました。

https://github.com/nablarch/nablarch-fw-scoped-dicontainer/blob/e045951bc5ac27789fedc0763b20314517907ffa/src/main/java/nablarch/fw/dicontainer/annotation/AnnotationMemberFactory.java

例外のjavadocコメントには、
「ファクトリメソッドで定義されるコンポーネントが指定された破棄メソッドを持っていなかった場合にスローされる例外」とありましたが、この用途の説明もよく理解できてないです。
（「ファクトリメソッドで定義されるコンポーネント」のところ）

**Comment by backpaper0** [comment]
Springの`@Bean`のようにメソッドでコンポーネント定義を出来るように考えていたときの消し忘れですね。
すみません。

メソッドでのコンポーネント定義はオーバースペックだなと思い直して機能自体を削除しました。
`LifeCycleMethodNotFoundException`自体も削除して貰ってかまいません。

**Comment by sambatriste** [comment]
なるほど。理解しました。この例外は削除することにします。
