### ISSUE TITLE
ContainerImplementer#getComponent(ComponentId)の用途

### ISSUE THREAD

**Issue by sambatriste** [nablarch/nablarch-fw-scoped-dicontainer#5]
ComponentIdを指定してコンポーネントを取得するメソッドですが、
どういうときに使うものかわかりませんでした。

https://github.com/nablarch/nablarch-fw-scoped-dicontainer/blob/f7d2258405e927aee16659e499aea0df68ce2a30/src/main/java/nablarch/fw/dicontainer/container/ContainerImplementer.java#L32

ComponentDefinition.Builderを素直に使っていくと、オブジェクト構築中にあえてComponentIdを取得（ComponentDefinition.Builder#id）しないかぎり、ComponentIdの参照が外部に渡されることがないように思われたので、ComponentIdを引数に取るgetComponentの使いみちがよくわかりませんでした。

無理やりテストを書いてみましたが、何をやっているのかよくわからないコードになったので、
質問しました。

＃ContainerImplementer#getComponentDefinition(ComponentId)も同様です。

**Comment by backpaper0** [comment]
#4 と同じくファクトリーメソッドによるコンポーネント定義をする機能を取りやめたときに削除しないといけなかったものですね。
すみません。

今は使っていなさそうです。

**Comment by backpaper0** [comment]
そうなると`ContainerImplementer`自体消してしまって`getComponent(ComponentKey<T>)`を`Container`に持っていってもいいかも知れないですね（`ComponentKey`自体は開発者に露出しちゃっても問題ないだろう、というぐらいに思っています）。

**Comment by sambatriste** [comment]
Containerインタフェースに統一できると、少し複雑さを減らせそうなこともあり、ContainerImplementerを消して、メソッドをpull upしようと思います。
